### PR TITLE
Add sortROIvoxels.m. The code sorts or keeps voxels in an ROI based on

### PR DESCRIPTION
**Pull request by steevelaquitaine**
Sort or keep voxels in an ROI based on certain parameters such as their r2 produced by an event-related analysis.

### CODE REVIEW

**Comment by dbirman** [comment]
Isn't this more appropriate to put into gru not mrtools?

**Comment by steevelaquitaine** [comment]
It doesn't aim to be specific to use in the lab but is for general use...but whichever find I guess

**Comment by francopestilli** [comment]
I know at least one person that would like to use it :)

**Comment by justingardner** [comment]
I would prefer to put things like this into gru until they have been fully tested by others in the lab. Franco, if you want to use, you should pull our gru repo.

**Pull request closed without merging**
